Repository elderanakain/pa165-formula-one-team, pull requests merged in 2018-12, with the labels that each got.

#52 Fix develop tests
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentParameterService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentParameterServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/EngineerService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/EngineerServiceImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/EngineerServiceImplTest.java
Labels: bug

#53 Update manager facade
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/ManagerFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/base/BaseEntityFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/base/BaseFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/base/BaseUserFacade.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentParameterService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/EngineerService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ManagerService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceParticipationService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/TestDriveService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseEntityService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseEntityServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseUserServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseEntityFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseEntityService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseUserFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseUserService.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseFacadeTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/DriverFacadeImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/ManagerServiceImplTests.java
Labels: enhancement

#54 Update services with a new architecture
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/DaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/component/ComponentDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImplTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/driver/DriverDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/engineer/EngineerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/manager/ManagerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/race/RaceDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/testDrive/TestDriveDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/entity/base/BaseEntityTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/entity/base/UserTest.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/BeanMappingServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CarSetupService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CarSetupServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CharacteristicsValueService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CharacteristicsValueServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentParameterService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/DriverFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseFacadeTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseServiceTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/config/ServiceConfigurationTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/DriverFacadeImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/BeanMappingServiceTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/CarSetupServiceImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/CharacteristicsValueServiceImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/ComponentServiceImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/DriverServiceImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/EngineerServiceImplTest.java
Labels: enhancement

#59 Changes for the component carsetup & driver
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/CarSetupFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/ComponentFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/DriverFacade.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CarSetupService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentParameterServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ManagerService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/DriverFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseFacadeTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/DriverFacadeImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
Labels: enhancement

#58 updates
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/RaceFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/RaceParticipationFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/TestDriveFacade.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/DriverFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseEntityFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentParameterFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/EngineerFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImplTest.java
Labels: enhancement

#76 Fix invalid user entity validation
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseUserServiceImpl.java
Labels: bug

#77 Fix component parameter name should not be unique
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentParameter.java
Labels: bug

#80 Fix date service test
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/date/DateServiceImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/date/DateServiceImplTest.java
Labels: bug

#78 Add rest module
  formulaoneteam-rest/pom.xml
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/AllowOriginInterceptor.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/ApiUris.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/RootWebContext.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/ServletInitializer.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/controllers/MainController.java
  formulaoneteam-rest/src/main/webapp/WEB-INF/web.xml
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/AllowOriginInterceptorTests.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/MainControllerTest.java
  pom.xml
Labels: REST, architecture, enhancement

#82 CRUD base controller
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/exceptions/EntityNotFoundException.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/base/BaseEntityFacade.java
  formulaoneteam-rest/pom.xml
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/controllers/base/BaseCrudController.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/controllers/base/CreatedEntityIdDTO.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/MainControllerTest.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/base/BaseCrudControllerTests.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/base/TestController.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/base/TestDTO.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/base/TestEntity.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseEntityServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseEntityFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseEntityService.java
Labels: REST, enhancement

#84 Fix CI script and falling tests
  .travis.yml
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentParameterFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImplTest.java
Labels: bug

#86 Add rest module configuration
  formulaoneteam-rest/pom.xml
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/ServletInitializer.java
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/controllers/MainController.java
Labels: REST, enhancement

#87 Add web module
  formulaoneteam-web/pom.xml
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/config/MySpringMvcConfig.java
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/config/MyStartInitializer.java
  formulaoneteam-web/src/main/webapp/WEB-INF/jsp/home.jsp
  formulaoneteam-web/src/main/webapp/WEB-INF/tags/a.tag
  formulaoneteam-web/src/main/webapp/WEB-INF/tags/pagetemplate.tag
  formulaoneteam-web/src/test/cz/muni/fi/pa165/mvc/config/MyStartInitializerTest.java
  pom.xml
Labels: architecture, web

#88 Remove unused dto
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/controllers/base/CreatedEntityIdDTO.java
Labels: bug

#89 Disable ApiUris creation
  formulaoneteam-rest/src/main/java/cz/muni/fi/pa165/rest/ApiUris.java
Labels: bug

#96 Fix date comparison making crash DateServiceImplTests
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/date/DateServiceImplTest.java
Labels: bug

#90 Navigation bar
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/controllers/CarsController.java
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/controllers/ComponentsController.java
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/controllers/DriversController.java
  formulaoneteam-web/src/main/java/cz/muni/fi/pa165/mvc/controllers/WorldChampionshipController.java
  formulaoneteam-web/src/main/resources/logback.xml
  formulaoneteam-web/src/main/webapp/WEB-INF/jsp/cars/list.jsp
  formulaoneteam-web/src/main/webapp/WEB-INF/jsp/components/list.jsp
  formulaoneteam-web/src/main/webapp/WEB-INF/jsp/drivers/list.jsp
  formulaoneteam-web/src/main/webapp/WEB-INF/jsp/world-championship/list.jsp
  formulaoneteam-web/src/main/webapp/WEB-INF/tags/pagetemplate.tag
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/config/MyStartInitializerTest.java
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/controllers/BaseControllerTest.java
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/controllers/CarsControllerTests.java
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/controllers/ComponentsControllerTests.java
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/controllers/DriversControllerTests.java
  formulaoneteam-web/src/test/java/cz/muni/fi/pa165/mvc/controllers/WorldChampionshipControllerTests.java
Labels: enhancement, web

#105 Fix nationality typo
  formulaoneteam-sample-data/src/main/java/cz/muni/fi/pa165/sample/data/SampleDataLoadingFacadeImpl.java
Labels: bug

#97 Add base class for rest controller tests
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/BaseControllerTests.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/MainControllerTest.java
  formulaoneteam-rest/src/test/java/cz/muni/fi/pa165/rest/controllers/base/BaseCrudControllerTests.java
Labels: REST, enhancement, tests

#108 Adding of favicon
  formulaoneteam-web/src/main/webapp/WEB-INF/tags/pagetemplate.tag
  formulaoneteam-web/src/main/webapp/favicon.ico
Labels: enhancement, web

#103 Update component and component parameter entity relationship to cascade
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Component.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/base/BaseFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
Labels: bug

#111 Fix only time stored in testdrive
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/TestDrive.java
Labels: bug
