Repository elderanakain/pa165-formula-one-team, pull requests merged in 2018-11, with the labels that each got.

#18 Add Engineer, EngineerSpecialization, ComponentType and ComponentPara…
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/engineer/EngineerDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentParameter.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentType.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Engineer.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/EngineerSpecialization.java
Labels: enhancement

#17 Add CarSetup and Component entities
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/Component.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/ComponentParameter.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/enums/ComponentType.java
Labels: enhancement

#20 Driver and characteristics entities and DAO
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/driver/DriverDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/driver/DriverDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CharacteristicsType.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CharacteristicsValue.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Driver.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/DriverStatus.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/driver/DriverDaoTest.java
Labels: enhancement

#23 Remove temporary entity ComponentParameter and use the real one
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/Component.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/ComponentParameter.java
Labels: bug

#16 Add RacePartictipation and TestDrive
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/Race/RaceDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/Race/RaceDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/TestDrive/TestDriveDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/TestDrive/TestDriveDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Driver.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Race.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/RaceParticipation.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/TestDrive.java
Labels: enhancement

#24 Refactor Component dao
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/Component.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/enums/ComponentType.java
Labels: bug, enhancement

#25 Tests for ComponentDao and CarSetupDao
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentParameter.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/Component.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/component/ComponentDaoTest.java
Labels: enhancement, tests

#21 Dao refactoring
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/AppContextConfig.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/DaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/UserDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/UserDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/engineer/EngineerDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/engineer/EngineerDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/manager/ManagerDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/manager/ManagerDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Engineer.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/EngineerSpecialization.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Manager.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/base/BaseEntity.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/base/User.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/DaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/TestEntity.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/TestEntityDaoImpl.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/manager/ManagerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/entity/base/UserTest.java
Labels: enhancement

#31 improve javadoc for dao interface classes
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/Race/RaceDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/TestDrive/TestDriveDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/Dao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/UserDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/driver/DriverDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/engineer/EngineerDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/manager/ManagerDao.java
Labels: enhancement

#28 Tests of RaceDao, RaceParticipationDao and TestDriveDao
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/Race/RaceDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/TestDrive/TestDriveDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Driver.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Race.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/RaceParticipation.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/TestDrive.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/base/User.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/component/Component.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/BaseTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/driver/DriverDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/race/RaceDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/raceParticipation/RaceParticipationDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/testDrive/TestDriveDaoTest.java
Labels: enhancement, tests

#32 Test DriverDao and CharacteriscticsDao
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/driver/DriverDaoImpl.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/BaseTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/driver/DriverDaoTest.java
Labels: enhancement, tests

#34 Add equivalence members for entities, add date to TestDrive entity
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDao.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CarSetup.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CharacteristicsValue.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Component.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentParameter.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Race.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/RaceParticipation.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/TestDrive.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/BaseTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/component/ComponentDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/testDrive/TestDriveDaoTest.java
Labels: bug, enhancement

#38 Add API and Service modules
  formulaoneteam-api/pom.xml
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/ManagerDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/UserDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/ManagerFacade.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/AppContextConfig.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/base/User.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/manager/ManagerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/entity/base/UserTest.java
  formulaoneteam-service/pom.xml
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/BeanMappingService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/BeanMappingServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ManagerService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ManagerServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/config/ServiceConfiguration.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/utils/Validator.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImplTest.java
  pom.xml
Labels: enhancement

#41 Race, RaceParticipation & TestDrive DTOs
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/RaceDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/RaceParticipationDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/TestDriveDTO.java
Labels: enhancement

#43 Adding CarSetupDTO and ComponentDTO
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/CarSetupDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/ComponentDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/ComponentParameterDTO.java
Labels: enhancement

#40 Add DriverService and DriverFacade for accessing driver information
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/DriverDetailDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/DriverListItemDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/DriverFacade.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/Race/RaceDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/TestDrive/TestDriveDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/base/DaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/carsetup/CarSetupDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/characteristics/CharacteristicsValueDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/component/ComponentDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/driver/DriverDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/engineer/EngineerDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/manager/ManagerDaoImpl.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/CharacteristicsValue.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/Driver.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/base/DaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImplTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/driver/DriverDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/engineer/EngineerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/manager/ManagerDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/race/RaceDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/testDrive/TestDriveDaoTest.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CharacteristicsValueService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CharacteristicsValueServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ManagerServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/exceptions/FormulaOneTeamException.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/DriverFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseFacadeTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/DriverFacadeImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ManagerFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/CharacteristicsValueServiceImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/DriverServiceImplTests.java
Labels: enhancement

#45 Adding CarSetup and Component services
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CarSetupService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/CarSetupServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/ComponentServiceImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/CarSetupServiceImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/ComponentServiceImplTest.java
Labels: enhancement

#44 Add Race RaceParticipation & TestDrive Services
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/RaceDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/RaceParticipationDTO.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/TestDriveDTO.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/dao/RaceParticipation/RaceParticipationDaoImpl.java
  formulaoneteam-service/.attach_pid27591
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/DriverServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceParticipationService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceParticipationServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/RaceServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/TestDriveService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/TestDriveServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseService.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/base/BaseServiceImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/exceptions/FormulaOneTeamException.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseServiceTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/base/BaseTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/DriverFacadeImplTests.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/CarSetupServiceImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/RaceParticipationServiceTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/RaceServiceTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/service/TestDriveServiceTest.java
Labels: enhancement

#49 Engineer dto
  .gitignore
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/EngineerDTO.java
Labels: enhancement

#48 Componentparameter dto
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/dto/ComponentParameterDTO.java
  formulaoneteam-persistence/src/main/java/cz/muni/fi/pa165/entity/ComponentParameter.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/component/ComponentDaoTest.java
  formulaoneteam-persistence/src/test/java/cz/muni/fi/pa165/dao/componentparameter/ComponentParameterDaoImplTest.java
Labels: enhancement

#47 RaceFacadeImpl RaceParticipationFacadeImpl TestDriveFacadeImpl & test's
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/RaceFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/RaceParticipationFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/TestDriveFacade.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/RaceParticipationFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/TestDriveFacadeImplTest.java
Labels: enhancement

#46 Add facade for CarSetup and Component
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/CarSetupFacade.java
  formulaoneteam-api/src/main/java/cz/muni/fi/pa165/facade/ComponentFacade.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImpl.java
  formulaoneteam-service/src/main/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImpl.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/CarSetupFacadeImplTest.java
  formulaoneteam-service/src/test/java/cz/muni/fi/pa165/service/facade/ComponentFacadeImplTest.java
Labels: enhancement
